//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""PlayerGround"",
            ""id"": ""bd124244-f7d3-4fa3-b03f-c9a0d3cfd605"",
            ""actions"": [
                {
                    ""name"": ""MouseLook"",
                    ""type"": ""Value"",
                    ""id"": ""68a05b8f-842c-480d-b1cf-7b73ed9c9503"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4b5b93f5-a6f9-4fea-8a7e-2b0280831a43"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7e31586c-d080-4ad3-b5c5-749bed4017b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""fc1cf25b-f6a8-4902-bbae-950ac1671406"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""515ca758-ee74-4cb7-beed-2da9c5db2dd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""8eadc36e-4b82-4353-8646-e561a117540f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""e96ec521-bacc-4040-b5a9-ea75a086d5f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""61ec5b84-6117-47d8-818f-43e32b4e5140"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""09979f72-6609-41e7-8d38-c91601a1aa63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleInventory"",
                    ""type"": ""Button"",
                    ""id"": ""d701d0f3-2781-48ff-aed7-d13c1834e394"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StackOne"",
                    ""type"": ""Button"",
                    ""id"": ""d964417f-6187-4253-91bf-909d23a388e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StackHalf"",
                    ""type"": ""Button"",
                    ""id"": ""1767f97b-e3e1-4d65-8693-97d3b5786526"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StackFast"",
                    ""type"": ""Button"",
                    ""id"": ""020678f8-ef44-4e93-9e9b-cb6331a1f694"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextSlot"",
                    ""type"": ""Value"",
                    ""id"": ""1f0c9875-ee2a-4136-94a6-c61b25234e50"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Slot1"",
                    ""type"": ""Button"",
                    ""id"": ""30de1e63-f627-414b-bc07-4accbb743f95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot2"",
                    ""type"": ""Button"",
                    ""id"": ""0e310a5e-2201-4b93-8463-86b8b43f0d96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot3"",
                    ""type"": ""Button"",
                    ""id"": ""e7316201-6d1f-451c-9b51-29d82edae28a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot4"",
                    ""type"": ""Button"",
                    ""id"": ""d485c049-8ed2-4818-9636-a19eb1f90c00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot5"",
                    ""type"": ""Button"",
                    ""id"": ""eb5cdde3-289d-4203-bbe0-fc0a892b2ee1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot6"",
                    ""type"": ""Button"",
                    ""id"": ""b4343c77-7cc0-42d8-a5b8-bf1e77dff9fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""d33bbc1e-796a-4bad-acc6-45a3fb3d4f77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""f9badb16-7358-4274-8e89-066b2748c615"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""090a1808-abf3-4cf5-940d-a5413f098ac9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ec5b48f7-b98b-4a20-b9a0-478cb3d4f6ee"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""74d240fb-c07e-4843-b6d3-f56191039547"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b939036e-7e73-473d-ad11-d50d0d02d51c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fef933e2-be4e-48eb-aa90-2eb31a205fa5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""62327401-5465-46e6-83c2-5f9525f9dfac"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e9c3b6be-9c9c-48b7-ad3d-86a625ad71a6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2f764d54-6ff8-4de8-92a3-5e31a58b5565"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f08d4346-e49d-4b3c-b329-5f3cb9fedd21"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b27658c8-eea8-466e-92bf-d3656feb963a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba2a9abc-063f-4cc4-890c-5cdf8b6624a8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d67fc3af-a816-400c-ad19-d0dfe5282ff9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""SecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""995a11c1-c46f-420a-a72e-9ca63a6561a4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16c7764e-d7ae-4329-8ee1-c53fdfd6ad12"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Default"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f61b5d3-032c-4087-a525-ab4c91169e1f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b95a8e2-f809-47a1-901d-e11ce3a5e673"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StackOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddc015dd-ea6b-489c-91cc-f53ac1566ada"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StackHalf"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143f72aa-a1d1-453b-b2df-fb6d4e464c40"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StackFast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e78491f3-a7cb-4316-9c98-a6d810def559"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86b96604-5bdd-4213-986d-585c73460577"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78704efb-692b-4d55-9289-98fad82bc7a0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b35016d8-e988-4b8d-9c25-a2e39aef4bd0"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90f873ea-6830-4d5f-bbe6-361479572333"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""062c028d-d972-437e-b5a2-b7a2693e3141"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7be0f316-da61-44c3-b7cc-6b1460f7da0b"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1418060f-33ad-40bf-8db8-279a77933355"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bd87e26-be59-444c-89a1-eec99bce27f8"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ceabb4cb-09fa-48d8-9671-1341c3a3f746"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Default"",
            ""bindingGroup"": ""Default"",
            ""devices"": []
        }
    ]
}");
        // PlayerGround
        m_PlayerGround = asset.FindActionMap("PlayerGround", throwIfNotFound: true);
        m_PlayerGround_MouseLook = m_PlayerGround.FindAction("MouseLook", throwIfNotFound: true);
        m_PlayerGround_Move = m_PlayerGround.FindAction("Move", throwIfNotFound: true);
        m_PlayerGround_Jump = m_PlayerGround.FindAction("Jump", throwIfNotFound: true);
        m_PlayerGround_Run = m_PlayerGround.FindAction("Run", throwIfNotFound: true);
        m_PlayerGround_Crouch = m_PlayerGround.FindAction("Crouch", throwIfNotFound: true);
        m_PlayerGround_PrimaryAction = m_PlayerGround.FindAction("PrimaryAction", throwIfNotFound: true);
        m_PlayerGround_SecondaryAction = m_PlayerGround.FindAction("SecondaryAction", throwIfNotFound: true);
        m_PlayerGround_Interact = m_PlayerGround.FindAction("Interact", throwIfNotFound: true);
        m_PlayerGround_Reload = m_PlayerGround.FindAction("Reload", throwIfNotFound: true);
        m_PlayerGround_ToggleInventory = m_PlayerGround.FindAction("ToggleInventory", throwIfNotFound: true);
        m_PlayerGround_StackOne = m_PlayerGround.FindAction("StackOne", throwIfNotFound: true);
        m_PlayerGround_StackHalf = m_PlayerGround.FindAction("StackHalf", throwIfNotFound: true);
        m_PlayerGround_StackFast = m_PlayerGround.FindAction("StackFast", throwIfNotFound: true);
        m_PlayerGround_NextSlot = m_PlayerGround.FindAction("NextSlot", throwIfNotFound: true);
        m_PlayerGround_Slot1 = m_PlayerGround.FindAction("Slot1", throwIfNotFound: true);
        m_PlayerGround_Slot2 = m_PlayerGround.FindAction("Slot2", throwIfNotFound: true);
        m_PlayerGround_Slot3 = m_PlayerGround.FindAction("Slot3", throwIfNotFound: true);
        m_PlayerGround_Slot4 = m_PlayerGround.FindAction("Slot4", throwIfNotFound: true);
        m_PlayerGround_Slot5 = m_PlayerGround.FindAction("Slot5", throwIfNotFound: true);
        m_PlayerGround_Slot6 = m_PlayerGround.FindAction("Slot6", throwIfNotFound: true);
        m_PlayerGround_Save = m_PlayerGround.FindAction("Save", throwIfNotFound: true);
        m_PlayerGround_Load = m_PlayerGround.FindAction("Load", throwIfNotFound: true);
        m_PlayerGround_Drop = m_PlayerGround.FindAction("Drop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerGround
    private readonly InputActionMap m_PlayerGround;
    private IPlayerGroundActions m_PlayerGroundActionsCallbackInterface;
    private readonly InputAction m_PlayerGround_MouseLook;
    private readonly InputAction m_PlayerGround_Move;
    private readonly InputAction m_PlayerGround_Jump;
    private readonly InputAction m_PlayerGround_Run;
    private readonly InputAction m_PlayerGround_Crouch;
    private readonly InputAction m_PlayerGround_PrimaryAction;
    private readonly InputAction m_PlayerGround_SecondaryAction;
    private readonly InputAction m_PlayerGround_Interact;
    private readonly InputAction m_PlayerGround_Reload;
    private readonly InputAction m_PlayerGround_ToggleInventory;
    private readonly InputAction m_PlayerGround_StackOne;
    private readonly InputAction m_PlayerGround_StackHalf;
    private readonly InputAction m_PlayerGround_StackFast;
    private readonly InputAction m_PlayerGround_NextSlot;
    private readonly InputAction m_PlayerGround_Slot1;
    private readonly InputAction m_PlayerGround_Slot2;
    private readonly InputAction m_PlayerGround_Slot3;
    private readonly InputAction m_PlayerGround_Slot4;
    private readonly InputAction m_PlayerGround_Slot5;
    private readonly InputAction m_PlayerGround_Slot6;
    private readonly InputAction m_PlayerGround_Save;
    private readonly InputAction m_PlayerGround_Load;
    private readonly InputAction m_PlayerGround_Drop;
    public struct PlayerGroundActions
    {
        private @PlayerInputs m_Wrapper;
        public PlayerGroundActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseLook => m_Wrapper.m_PlayerGround_MouseLook;
        public InputAction @Move => m_Wrapper.m_PlayerGround_Move;
        public InputAction @Jump => m_Wrapper.m_PlayerGround_Jump;
        public InputAction @Run => m_Wrapper.m_PlayerGround_Run;
        public InputAction @Crouch => m_Wrapper.m_PlayerGround_Crouch;
        public InputAction @PrimaryAction => m_Wrapper.m_PlayerGround_PrimaryAction;
        public InputAction @SecondaryAction => m_Wrapper.m_PlayerGround_SecondaryAction;
        public InputAction @Interact => m_Wrapper.m_PlayerGround_Interact;
        public InputAction @Reload => m_Wrapper.m_PlayerGround_Reload;
        public InputAction @ToggleInventory => m_Wrapper.m_PlayerGround_ToggleInventory;
        public InputAction @StackOne => m_Wrapper.m_PlayerGround_StackOne;
        public InputAction @StackHalf => m_Wrapper.m_PlayerGround_StackHalf;
        public InputAction @StackFast => m_Wrapper.m_PlayerGround_StackFast;
        public InputAction @NextSlot => m_Wrapper.m_PlayerGround_NextSlot;
        public InputAction @Slot1 => m_Wrapper.m_PlayerGround_Slot1;
        public InputAction @Slot2 => m_Wrapper.m_PlayerGround_Slot2;
        public InputAction @Slot3 => m_Wrapper.m_PlayerGround_Slot3;
        public InputAction @Slot4 => m_Wrapper.m_PlayerGround_Slot4;
        public InputAction @Slot5 => m_Wrapper.m_PlayerGround_Slot5;
        public InputAction @Slot6 => m_Wrapper.m_PlayerGround_Slot6;
        public InputAction @Save => m_Wrapper.m_PlayerGround_Save;
        public InputAction @Load => m_Wrapper.m_PlayerGround_Load;
        public InputAction @Drop => m_Wrapper.m_PlayerGround_Drop;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGround; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGroundActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerGroundActions instance)
        {
            if (m_Wrapper.m_PlayerGroundActionsCallbackInterface != null)
            {
                @MouseLook.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnMouseLook;
                @MouseLook.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnMouseLook;
                @MouseLook.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnMouseLook;
                @Move.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnJump;
                @Run.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnRun;
                @Crouch.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnCrouch;
                @PrimaryAction.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnPrimaryAction;
                @PrimaryAction.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnPrimaryAction;
                @PrimaryAction.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnPrimaryAction;
                @SecondaryAction.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSecondaryAction;
                @Interact.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnInteract;
                @Reload.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnReload;
                @ToggleInventory.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnToggleInventory;
                @ToggleInventory.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnToggleInventory;
                @ToggleInventory.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnToggleInventory;
                @StackOne.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackOne;
                @StackOne.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackOne;
                @StackOne.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackOne;
                @StackHalf.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackHalf;
                @StackHalf.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackHalf;
                @StackHalf.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackHalf;
                @StackFast.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackFast;
                @StackFast.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackFast;
                @StackFast.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnStackFast;
                @NextSlot.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnNextSlot;
                @NextSlot.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnNextSlot;
                @NextSlot.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnNextSlot;
                @Slot1.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot1;
                @Slot1.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot1;
                @Slot1.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot1;
                @Slot2.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot2;
                @Slot2.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot2;
                @Slot2.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot2;
                @Slot3.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot3;
                @Slot3.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot3;
                @Slot3.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot3;
                @Slot4.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot4;
                @Slot4.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot4;
                @Slot4.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot4;
                @Slot5.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot5;
                @Slot5.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot5;
                @Slot5.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot5;
                @Slot6.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot6;
                @Slot6.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot6;
                @Slot6.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSlot6;
                @Save.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSave;
                @Save.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSave;
                @Save.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnSave;
                @Load.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnLoad;
                @Load.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnLoad;
                @Load.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnLoad;
                @Drop.started -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_PlayerGroundActionsCallbackInterface.OnDrop;
            }
            m_Wrapper.m_PlayerGroundActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseLook.started += instance.OnMouseLook;
                @MouseLook.performed += instance.OnMouseLook;
                @MouseLook.canceled += instance.OnMouseLook;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @PrimaryAction.started += instance.OnPrimaryAction;
                @PrimaryAction.performed += instance.OnPrimaryAction;
                @PrimaryAction.canceled += instance.OnPrimaryAction;
                @SecondaryAction.started += instance.OnSecondaryAction;
                @SecondaryAction.performed += instance.OnSecondaryAction;
                @SecondaryAction.canceled += instance.OnSecondaryAction;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @ToggleInventory.started += instance.OnToggleInventory;
                @ToggleInventory.performed += instance.OnToggleInventory;
                @ToggleInventory.canceled += instance.OnToggleInventory;
                @StackOne.started += instance.OnStackOne;
                @StackOne.performed += instance.OnStackOne;
                @StackOne.canceled += instance.OnStackOne;
                @StackHalf.started += instance.OnStackHalf;
                @StackHalf.performed += instance.OnStackHalf;
                @StackHalf.canceled += instance.OnStackHalf;
                @StackFast.started += instance.OnStackFast;
                @StackFast.performed += instance.OnStackFast;
                @StackFast.canceled += instance.OnStackFast;
                @NextSlot.started += instance.OnNextSlot;
                @NextSlot.performed += instance.OnNextSlot;
                @NextSlot.canceled += instance.OnNextSlot;
                @Slot1.started += instance.OnSlot1;
                @Slot1.performed += instance.OnSlot1;
                @Slot1.canceled += instance.OnSlot1;
                @Slot2.started += instance.OnSlot2;
                @Slot2.performed += instance.OnSlot2;
                @Slot2.canceled += instance.OnSlot2;
                @Slot3.started += instance.OnSlot3;
                @Slot3.performed += instance.OnSlot3;
                @Slot3.canceled += instance.OnSlot3;
                @Slot4.started += instance.OnSlot4;
                @Slot4.performed += instance.OnSlot4;
                @Slot4.canceled += instance.OnSlot4;
                @Slot5.started += instance.OnSlot5;
                @Slot5.performed += instance.OnSlot5;
                @Slot5.canceled += instance.OnSlot5;
                @Slot6.started += instance.OnSlot6;
                @Slot6.performed += instance.OnSlot6;
                @Slot6.canceled += instance.OnSlot6;
                @Save.started += instance.OnSave;
                @Save.performed += instance.OnSave;
                @Save.canceled += instance.OnSave;
                @Load.started += instance.OnLoad;
                @Load.performed += instance.OnLoad;
                @Load.canceled += instance.OnLoad;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
            }
        }
    }
    public PlayerGroundActions @PlayerGround => new PlayerGroundActions(this);
    private int m_DefaultSchemeIndex = -1;
    public InputControlScheme DefaultScheme
    {
        get
        {
            if (m_DefaultSchemeIndex == -1) m_DefaultSchemeIndex = asset.FindControlSchemeIndex("Default");
            return asset.controlSchemes[m_DefaultSchemeIndex];
        }
    }
    public interface IPlayerGroundActions
    {
        void OnMouseLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnPrimaryAction(InputAction.CallbackContext context);
        void OnSecondaryAction(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnToggleInventory(InputAction.CallbackContext context);
        void OnStackOne(InputAction.CallbackContext context);
        void OnStackHalf(InputAction.CallbackContext context);
        void OnStackFast(InputAction.CallbackContext context);
        void OnNextSlot(InputAction.CallbackContext context);
        void OnSlot1(InputAction.CallbackContext context);
        void OnSlot2(InputAction.CallbackContext context);
        void OnSlot3(InputAction.CallbackContext context);
        void OnSlot4(InputAction.CallbackContext context);
        void OnSlot5(InputAction.CallbackContext context);
        void OnSlot6(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
        void OnLoad(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
    }
}
